# https://travis-ci.org/sourcedelica/unix-cb
language: c
compiler:
  - clang
  - gcc
before_script:
  - sudo pip install pexpect --use-mirrors
  - ./autogen.sh
script:
  - ./configure
  - make && make check || (cat test-suite.log && false)
